# Generated by Django 5.1.4 on 2024-12-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicios',
            name='nivel_dificuldade',
        ),
    ]
